BEGIN;

DROP TABLE IF EXISTS
"names",
"adjectives",
"verbs",
"complements"
CASCADE;


CREATE TABLE "names" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    "name" VARCHAR (50)
);

CREATE TABLE "adjectives" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    "name" VARCHAR (50)
);

CREATE TABLE "verbs" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    "name" VARCHAR (50)
);

CREATE TABLE "complements" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    "name" VARCHAR (50)
);

INSERT INTO "names" ("name") VALUES
('la mairie de Neuilly-sur-Seine'),
('une huître'),
('Julie Andrieu'),
('Jacky et sa Subaru Impreza'),
('la gendarmerie hollandaise'),
('un chauve'),
('Simon'),
('2 chatons');

INSERT INTO "adjectives" ("name") VALUES
('bien cuit'),
('blond'),
('guilleret'),
('ankylosé'),
('blafard'),
('rasé de près'),
('amputé d''un doigt');

INSERT INTO "verbs" ("name") VALUES
('consulte'),
('franchit'),
('cuisine'),
('remet en question'),
('s''immole pour protester contre'),
('enduit de confiture'),
('instaure'),
('déguste');

INSERT INTO "complements" ("name") VALUES
('un seau en plastique'),
('la consommation de café'),
('Yann'),
('3 roues de voiture'),
('2 mains gauches'),
('un skieur débutant'),
('la Mer Noire');

COMMIT;
